### ISSUE TITLE
Arabic pasting issue

### ISSUE THREAD

**Issue by curya** [Mercury13/unicodia#324]
If I try to copy الله from [here](https://ar.wikipedia.org/wiki/%D8%A7%D9%84%D9%84%D9%87_(%D9%83%D9%84%D9%85%D8%A9)) and paste it into Unicodia, I get this:
![image](https://github.com/Mercury13/unicodia/assets/71131343/a09480c2-d9a0-42a6-8a4a-4a686b29bd6d)

It's *should* look like this:
![image](https://github.com/Mercury13/unicodia/assets/71131343/a19c44ee-3731-42d8-b056-623947b5f1d4)

**Comment by Mercury13** [comment]
Not a bug.
![image](https://github.com/Mercury13/unicodia/assets/10164882/4ba78f4c-1ac4-4278-afa1-1eeaab925678)
Address 5BFBF:
A = D8 A7
L = D9 84, twice
H = D9 87
␣ = 20

I tried to write this in LibreWriter, and got this (font is Amiri)
![image](https://github.com/Mercury13/unicodia/assets/10164882/c2d5ea46-9c5c-48e9-8b3a-a2fe4fda830b)
As soon as I add H, it ligates into ALLAH.
And it’s a feature rather than bug.
Amiri and KacstBook do ligate. Noto and Scheherazade do not.
![image](https://github.com/Mercury13/unicodia/assets/10164882/cd993218-12df-4036-b80a-5ddc5109541c)

**Comment by Mercury13** [comment]
![image](https://github.com/Mercury13/unicodia/assets/10164882/9b8ecc83-f25e-42c4-9be7-c50d325c4788)
This is the same Allah whose font changed to Noto via debugger.

**Comment by Mercury13** [comment]
Newest fonts: Scheherazade New does ligate, Noto does not.

**Comment by Mercury13** [comment]
@curya, you’d better post an issue to Noto that it does not ligate.

**Comment by curya** [comment]
@Mercury13 Thanks for looking into this. I posted an issue on the Noto Arabic GitHub.
