### ISSUE TITLE
Update Noto Sans Kawi (U+11F5A Kawi Sign Nutka)

### ISSUE THREAD

**Issue by nataliakeniganti** [Mercury13/unicodia#392]

**Comment by Mercury13** [comment]
Call Noto, I checked: nukta is not yet implemented.

The problem is: editing TTF will kill some tables almost for sure or introduce unwanted interactions, and there’s no way to ensure that the font is still usable, even if the nukta itself is unusable. Especially Tibetan, this is one of reasons why I switched Noto → BabelStone.
Some sources are from software that exists on Mac only.
That’s why I make patch fonts or Funky rather than edit Noto.

About nukta: what does it mean? It’s a consonant (usually from loanwords) that does not exists in initial language. That means: nukta should interact with all vowel marks and virama, and probably with anusvara. Very hard.

**Comment by Mercury13** [comment]
…I forgot: nukta sometimes exists in lesser languages served with script.

**Comment by nataliakeniganti** [comment]
Support the
𑽚

**Comment by Mercury13** [comment]
Natalia, nukta IS PRESENT AS A GAG GLYPH. I cannot support is properly, but as you don’t know what is a Brahmic abugida, that should be enough for you.
![image](https://github.com/user-attachments/assets/e1d2a53f-dbaf-4aab-ba96-49864c88a4bf)

**Comment by Mercury13** [comment]
In 2.8.7 there’ll be updated Scheherazade, and five U16 Arabic characters will be COMPLETELY supported.
Kawi… it’s seemingly on hold.
