### ISSUE TITLE
terrible program windows 11 

### ISSUE THREAD

**Issue by nataliakeniganti** [Mercury13/unicodia#414]
question: Not working unicodia

**Comment by Mercury13** [comment]
Natalia, works for me!
Please make a screenshot, or write what’s happening.
Possible problems:
- I did not sign program, and Windows (even 10) really suspects it
- Something’s happening with built-in libraries
- Because of Qt’s bad implementation of table, I made selected object with a button, and W11 draws it badly
- No dark theme

**Comment by nataliakeniganti** [comment]
Fixed ui.
